<a href="https://colab.research.google.com/github/cnyakundi/sampling/blob/master/Python_Programming_Simple_Random_Sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="green">To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.</font>

# Python Programming:  Simple Random Sampling


## Importing our Libraries

In [1]:
# importing numpy
import numpy as np

# importing pandas
import pandas as pd

# importing random module
# we will use random.sample() function to return a k length 
# list of unique elements chosen from our population
import random

## 1.0 Selecting More than One item from a List

In [2]:
# Example 1
# ---
# Selecting more than one item from a list 
# ---
#

list = [20, 40, 80, 100, 120]
print ("Choosing 3 random items from a list using sample function", random.sample(list, k=3))

list = [20, 40, 20, 20, 20]
print ("Choosing 3 random items from a list using sample function",random.sample(list, k=3))

# As you can see we pass k=3 to choose 3 random elements from a list. 
# In return, we got a list of 3 random items.

Choosing 3 random items from a list using sample function [100, 80, 40]
Choosing 3 random items from a list using sample function [40, 20, 20]


### <font color="green"> 1.0 Challenges</font>

In [5]:
# Challenge 1
# ---
# Question: Create a list containing 10 counties in Kenya 
# then select 2 random counties from the list.
# ---
# 
counties = ['Nairobi', 'Kisumu', 'Mombasa', 'Narok', 'Kisii', 'Nyamira', 'Bungoma', 'Kilifi', 'Meru', 'Garissa']

sampled_counties=random.sample(counties, k=2)

print(sampled_counties)



['Nyamira', 'Kisumu']


## 2.0  Selecting the Random Sample from Dictionary

In [6]:
# Example 1
# ---
# We can select a random key-value pair from the dictionary as shown 
# ---
#
marks_dict = {
  "Kelly": 55,
  "jhon": 70,
  "Donald": 60,
  "Lennin" :50
}

print ("Choosing 2 random items from a dictionary using sample method ", random.sample(marks_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('jhon', 70), ('Donald', 60)]


### <font color="green">2.0 Challenges</font>

In [12]:
# Challenge 1
# ---
# A caterer offers three different food packages; 
# bronze package: starch:rice stew:chicken curry vegetable:cabbages desert:melon
# silver package: starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas
# gold package: starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart
# Create a dictionary that stores the above information and select a sample of size 2 

bronze={'starch':'rice', 'stew':'chicken curry', 'vegetable':'cabbages', 'desert':'melon'}

silver= {'starch':'rice and chappati',  'stew':'beef curry', 'vegetable':'spinach', 'desert': 'melon and bananas'}

gold ={ 'starch':'rice', 'chappati and mukimo stew': 'beef curry', 'vegetable':'spinach and managu', 'desert': 'tart'}

all_meals=['bronze','silver','gold']

print(random.sample(all_meals,k=2))

['silver', 'bronze']


## 3.0 Selecting a Random Sample with Replacement to including repetition


In [15]:
# Example 1
# ---
# We can select a random sample with replacement to include repetition as shown below
# ---
# 
names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]

print("random sample with replacement to including repetition ", random.choices(names, k=3))

random sample with replacement to including repetition  ['Andre', 'Novac', 'Roger']


### <font color="green">3.0 Challenges</font>

In [19]:
# Challenge 1
# ---
# Question: Select a random sample of 3 with replacement to include replacement from the 
# following list of months
# ---
#

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']

print(random.choices(names, k=3))

['Martina', 'Roger', 'Novac']


## 4.0 Selecting a Random Sample from a Range of Integers

In [21]:
# Example 1
# ---
# We can select a random sample from a range of integers as shown below
# ---
# 

weight_set = {40, 50, 55, 65, 75, 80}

print ("Choosing 4 random items from a set ", random.sample(weight_set, k=4))

Choosing 4 random items from a set  [50, 80, 55, 40]


### <font color="green">4.1 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select a random sample from a range of integers as shown below
# --- 
# 
weight_set = {4, 5, 6, 7, 8, 9, 10}



## 5.0 Selecting a Sample Array from a Large multidimensional Array



In [48]:
# Example 1
# ---
# We can select a sample array from a large multidimensional array as shown
# ---
# 

array = np.array([[2 ,4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]]) 
print("Printing 2D Array")
print(array)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)

for i in randomRows:
  print(array[i,:])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Selecting multiple random rows from the 2D array
[ 8 16 24]
[ 8 16 24]


### <font color="green">5.0 Challenges</font>

In [51]:
# Challenge 1
# ---
# Question: Select two arrays from the given multidimensional array
# ---
# 

a = [[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [1 ,2 , 4, 5, 6], [5, 10, 15, 20, 25], [6, 12, 18, 24, 30], [7, 14, 21, 28, 35]]  

array=np.array(a)

print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)

for i in randomRows:
  print(array[i,:])

Selecting multiple random rows from the 2D array
[ 5 10 15 20 25]
[ 2  4  6  8 10]


## 6.0 Selecting Random Samples from a Dataset

In [52]:
# Example 1
# ---
# Selecting a random sample from the following medical appointments dataset
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
# 

# Loading the dataset
medical_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")

# Determining the size
print(medical_df.shape)


# Previewing the dataset
print(medical_df.head())

# Selecting the sample 
medical_sample = medical_df.sample(n = 10, replace="False")
print(medical_sample)

(110527, 14)
      PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No
3  8.679512e+11        5642828      F  ...       0            0       No
4  8.841186e+12        5642494      F  ...       0            0       No

[5 rows x 14 columns]
          PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
91053  1.631652e+12        5623825      M  ...       0            0      Yes
25199  8.215792e+12        5502043      M  ...       0            1      Yes
34428  7.363567e+10        5671838      F  ...       0            0       No
6929   1.442659e+12        5578887      M  ...       0            0      Yes
72966  4.518474e+14        5652841      M  ...       0            0       No
71812  5.545276e+13        5659175      F  ...       0          

### <font color="green">6.0 Challenges </font>

In [53]:
# Challenge 1
# ---
# Select a random sample of 10 from the given dataset below 
# ---
url = "http://bit.ly/DSRussianInvestigation"

df=pd.read_csv(url)

# Determining the size
print(df.shape)


# Previewing the dataset
print(df.head())

# Selecting the sample 
my_sample = df.sample(n = 10, replace="False")
print(my_sample)

(194, 13)
  investigation investigation-start  ... american      president
0     watergate          1973-05-19  ...     True  Richard Nixon
1     watergate          1973-05-19  ...     True  Richard Nixon
2     watergate          1973-05-19  ...     True  Richard Nixon
3     watergate          1973-05-19  ...     True  Richard Nixon
4     watergate          1973-05-19  ...     True  Richard Nixon

[5 rows x 13 columns]
    investigation investigation-start  ... american         president
21      watergate          1973-05-19  ...     True     Richard Nixon
164        russia          2017-05-17  ...    False      Donald Trump
25      watergate          1973-05-19  ...     True     Richard Nixon
98         pierce          1990-03-01  ...     True  George H.W. Bush
115    whitewater          1994-08-05  ...     True      Bill Clinton
190        russia          2017-05-17  ...    False      Donald Trump
56      watergate          1973-05-19  ...     True     Richard Nixon
192        russia

In [54]:
# Challenge 2
# ---
# A medical company would like to follow up with 50 patients who never showed up for appointments 
# but received an sms. Select a random sample from such patients given the medical dataset below 
# ---
url = "http://bit.ly/MedicalAppointmentsDataset"

df=pd.read_csv(url)

# Determining the size
print(df.shape)


# Previewing the dataset
print(df.head())

# Selecting the sample 
my_sample = df.sample(n = 10, replace="False")
print(my_sample)


(110527, 14)
      PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No
3  8.679512e+11        5642828      F  ...       0            0       No
4  8.841186e+12        5642494      F  ...       0            0       No

[5 rows x 14 columns]
           PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
6409    4.614829e+13        5732487      M  ...       0            1       No
741     7.429386e+14        5501940      F  ...       0            1      Yes
82699   7.785643e+14        5634071      F  ...       0            1       No
85585   8.585260e+14        5700080      F  ...       0            1       No
103353  5.335251e+11        5716928      F  ...       0            1       No
82566   3.626848e+13        5742486      F  ...       0   